### ISSUE TITLE
ERROR Audio device not found

### ISSUE THREAD

**Issue by gamer123123123** [MrHuu/devilutionX-3ds#6]
It happens when I open the game

It says error
And when I press the button A on 3ds it closes

Does anyone got a fix?

**Comment by AJenbo** [comment]
you need to add the audio firmware for your device

**Comment by gamer123123123** [comment]
where do i get that? @AJenbo

**Comment by gamer123123123** [comment]
Do you got a link for it?

**Comment by AJenbo** [comment]
Now that I think about it that might only be the case for using an emulator, the file is called dspfirm.cdc, I think you have to extract it from your device.

**Comment by AJenbo** [comment]
https://github.com/Cruel/DspDump

**Comment by MrHuu** [comment]
Like AJenbo said, you need to dump the firmware from your DSP chip.

Running the software linked to dumps the firmware to your SD card to: 'sd:/3ds/dspfirm.cdc'
Just leave the file there. You can remove the 'DspDump.3dsx' when finished.
This process is required for most .cia homebrew.

When i get to it, i'll add a proper warning when the dump is missing.

**Comment by gamer123123123** [comment]
Worked I had a app that does it already installed thanks closing this
