### ISSUE TITLE
Issue with warrior class and plate type armor

### ISSUE THREAD

**Issue by rayhern** [MrHuu/devilutionX-3ds#8]
**Describe**
When using the warrior and having "plate" type armor (any armor that changes character to final form of armor) causes game to crash when talking to griswold or pepin.

**To Reproduce**
1. Get plate armor.
2. start a new game with character.
3. talk to griswold pepin and even cain will cause the game to freeze.

**Expected behavior**
No freezing

**Comment by rayhern** [comment]
This could also be an issue with the "idle" movement of the player in plate armor form. I have noticed the game freezes when left in town.

**Comment by rayhern** [comment]
I tried emptying most of my inventory but still crashes when talking in town mostly with cain and pepin the healer. This is on both the diablo and hellfire builds

**Comment by AJenbo** [comment]
@rayhern can you attach a save game?

**Comment by rayhern** [comment]
Yes i will attach save game as soon as I get home. Seems like it could be a memory issue even as I have noticed it doesnt start happening until around character level 20

**Comment by rayhern** [comment]
It never happens in dungeons just in towns when talking to people or standing still too long

**Comment by MrHuu** [comment]
Thanks for reporting.
As AJenbo already said, a savegame would help a lot.

**Comment by rayhern** [comment]
This issue was resolved by using a different set of mpqs.
