### ISSUE TITLE
How can we use mod modules with this?

### ISSUE THREAD

**Issue by brunocar** [MrHuu/devilutionX-3ds#9]
I just wanted to know if i could use some QoL modules with this like we can in desktop, if so, how to do so.

**Comment by AJenbo** [comment]
What modules? You can apply patches if you want.

**Comment by brunocar** [comment]
Yes, but how do i make them work with this? is it the same process as the main builds?

**Comment by AJenbo** [comment]
I do not know what you are thinking about

**Comment by brunocar** [comment]
https://github.com/diasurgical/devilutionX/blob/master/docs/mods.md

**Comment by AJenbo** [comment]
Ok, the word module through me of here. 

if mod in question didn't provide pre build images for 3ds you will need to cherry pick the patches and make a build your self. Same as if you wanted to combine some of them etc

**Comment by brunocar** [comment]
Oh ok, thanks, dang, time to reinstall visual studio i guess.
